// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadAllExpenses() {
  return window['go']['main']['App']['ReadAllExpenses']();
}

export function ReadAllIncomes() {
  return window['go']['main']['App']['ReadAllIncomes']();
}

export function RegisterTransaction(arg1) {
  return window['go']['main']['App']['RegisterTransaction'](arg1);
}
