// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ReadAllIncomes():Promise<Array<model.Transaction>>;

export function RegisterTransaction(arg1:model.Transaction):Promise<boolean>;
